add test for penetrate()
software-students-fall2022/python-package-exercise-project-3-team-13 pull request #19
Opened 2022-11-08 18:28 UTC by EV9H

2022-11-08 22:51 UTC, bxw201 requested changes

2022-11-08 22:51 UTC, bxw201 commented on tests/test_penetrate.py
> +class TestConsole:
This test suite is currently testing the console package's code and not our own code

2022-11-08 22:51 UTC, bxw201 commented on tests/test_penetrate.py
> +class TestPyfiglet:
Same with this one. We should be calling our own written functions from the tests.

2022-11-08 22:51 UTC, bxw201 commented on tests/test_penetrate.py
> +class TestPenetrate:
I think this is closer to what we're looking for. We need three tests per function. At this point, just to make the requirements in time, we should focus on testing specifically the penetrate function, perhaps for different inputs.

2022-11-09 03:20 UTC, bxw201 approved these changes
lgm

2022-11-09 03:34 UTC, Zackdan0227 approved these changes

2022-11-09 03:36 UTC, merged